# Shared by every bench: building the nodes, the codec, and the test runs.
#
# Benches call these recipes from their own justfiles; `cd <bench> && just` is
# where to start.

set shell := ["bash", "--noprofile", "--norc", "-euo", "pipefail", "-c"]

CANTOOLS := "41.3.1"
CANOPEN_EDITOR := "v4.2.3"
DOTNET_SDK := "mcr.microsoft.com/dotnet/sdk:8.0@sha256:78235e09001f52b6592c458ac010775ebac6725422e80cd0c1650590f67b2743"
# The Zephyr tag west.yml pins, so the toolchain is built for the same one.
ZEPHYR := `sed -n '/- name: zephyr$/,/revision:/s/^ *revision: *//p' west.yml`
# Tagged by the Dockerfile's content too, so an unchanged image is never rebuilt
# and a changed Dockerfile always is.
TOOLCHAIN := "zelos-examples-toolchain:" + ZEPHYR + "-" + `shasum -a 256 toolchain/Dockerfile | cut -c1-12`
BOARD := "nucleo_h753zi"
# The part on that board, for probe-rs.
CHIP := "STM32H753ZITx"
# The Docker volume holding the west workspace, or an absolute host path to
# bind instead. Override to build two trees at once.
WORKSPACE := env("ZELOS_WEST_VOLUME", "zxws")

# Show the available recipes.
default:
    @just --list --unsorted

# Build one node into an ELF. ELF is relative to where just was run.
build NODE ELF *ARGS: _toolchain _west
    #!/usr/bin/env bash
    set -euo pipefail
    elf="{{ join(invocation_directory(), ELF) }}"
    name=$(basename "$elf" .elf)
    mkdir -p "$(dirname "$elf")"
    # An XCP build's A2L, written by the build, lands beside the ELF as <name>.a2l.
    a2l="for f in /workspace/build/$name/zephyr/*.a2l; do \
           [ ! -f \"\$f\" ] || cp \"\$f\" /out/$name.a2l; done"
    echo "==> building $name"
    docker run --rm --user root \
        -v {{ WORKSPACE }}:/workspace -v "$PWD:/workspace/zelos-examples:ro" \
        -v "$(dirname "$elf"):/out" {{ TOOLCHAIN }} \
        bash -c "cd /workspace && west build -p always -b {{ BOARD }} \
                  -d /workspace/build/$name zelos-examples/nodes/{{ NODE }} {{ ARGS }} \
                  && cp /workspace/build/$name/zephyr/zephyr.elf /out/$name.elf \
                  && $a2l"

# Regenerate each CAN codec, lib/codec_<name>/, from dbc/<name>.dbc.
# Deterministic: no timestamps.
dbc:
    # cantools stamps the generation date into a header comment, which would
    # make every regeneration differ. The version stays; the date goes.
    docker run --rm -v "$PWD:/w" -w /w python:3.12-slim bash -euc \
        'pip install --quiet cantools=={{ CANTOOLS }} \
         && for dbc in dbc/*.dbc; do \
              name=$(basename "$dbc" .dbc); out=lib/codec_$name; \
              python -m cantools generate_c_source --use-float -o "$out" "$dbc"; \
              sed -i -E "s/(generated by cantools version [0-9.]+) .*[0-9]{4}\./\1./" \
                "$out/$name.h" "$out/$name.c"; \
              chown --reference="$dbc" "$out/$name.h" "$out/$name.c"; \
              echo "$out/ regenerated from $dbc"; \
            done'

# Regenerate a CANopen node's object dictionary (od/CO_OD.c, od/CO_OD.h) from
# its EDS. Builds CANopenEditor's command-line exporter at a fixed tag.
canopen-od NODE:
    docker run --rm -v "$PWD/nodes/{{ NODE }}/od:/od" {{ DOTNET_SDK }} bash -euc \
        'git clone --quiet --branch {{ CANOPEN_EDITOR }} https://github.com/CANopenNode/CANopenEditor /src \
         && dotnet publish --verbosity quiet -clp:ErrorsOnly -c Release -f net8.0 -o /edssharp /src/EDSSharp/EDSSharp.csproj \
         && dotnet /edssharp/EDSSharp.dll --infile /od/{{ NODE }}.eds --outfile /od/CO_OD.c --type CanOpenNode \
         && chown --reference=/od/{{ NODE }}.eds /od/CO_OD.c /od/CO_OD.h'
    @echo "nodes/{{ NODE }}/od/ regenerated from {{ NODE }}.eds"

# Build every node variant for the board and run every ztest suite. Reports go
# to twister-out/.
#
# The board has no simulator here, so its builds are build-only; unit tests
# run on native_sim, 64-bit so no 32-bit host libraries are needed.
twister: _toolchain _west
    #!/usr/bin/env bash
    set -euo pipefail
    roots=()
    for dir in nodes tests; do
        [ -d "$dir" ] && roots+=(-T "zelos-examples/$dir")
    done
    mkdir -p twister-out
    # Root in the container, so hand the reports back to whoever ran this.
    docker run --rm --user root \
        -v {{ WORKSPACE }}:/workspace -v "$PWD:/workspace/zelos-examples:ro" \
        -v "$PWD/twister-out:/out" {{ TOOLCHAIN }} \
        bash -c "cd /workspace && rm -rf /out/* \
                  && { west twister ${roots[*]} -p {{ BOARD }} -p native_sim/native/64 \
                         -O /out --no-clean --inline-logs; status=\$?; } \
                  ; chown -R $(id -u):$(id -g) /out; exit \$status"

# Run a testing/ suite against nodes on a Renode bench, then tear it down.
# ELFS are relative to where just was run; each runs as one node.
test-bench SUITE +ELFS:
    #!/usr/bin/env bash
    set -euo pipefail
    elfs=$(mktemp -d)
    # A project per run, so concurrent runs get their own bus.
    compose=(docker compose -p "bench-$$" -f bench/compose.yaml)
    trap '"${compose[@]}" down --remove-orphans --volumes >/dev/null 2>&1; rm -rf "$elfs"' EXIT
    names=()
    for elf in {{ ELFS }}; do
        name=$(basename "$elf")
        [ ! -e "$elfs/$name" ] || { echo "two ELFs named $name" >&2; exit 2; }
        [[ $elf = /* ]] || elf="{{ invocation_directory() }}/$elf"
        cp "$elf" "$elfs/$name"
        names+=("$name")
        # An XCP build's A2L sits beside its ELF; the suite finds it in /elf.
        [ ! -f "${elf%.elf}.a2l" ] || cp "${elf%.elf}.a2l" "$elfs/"
    done
    export BENCH_ELF_DIR=$elfs BENCH_ELFS="${names[*]}"
    "${compose[@]}" up -d --wait renode || { "${compose[@]}" logs renode | tail -40; exit 1; }
    # --no-deps: recreating the bus would strand the nodes in the old namespace.
    "${compose[@]}" run --rm --no-deps tester "suites/{{ SUITE }}"

# Flash a node with probe-rs, then run testing/ suites on a physical channel.
# ELF is relative to where just was run.
hil ELF CHANNEL +SUITES:
    #!/usr/bin/env bash
    set -euo pipefail
    elf="{{ join(invocation_directory(), ELF) }}"
    # Under reset: a running image can idle the core out of reach of SWD.
    probe-rs download --chip {{ CHIP }} --connect-under-reset --verify "$elf"
    probe-rs reset --chip {{ CHIP }} --connect-under-reset
    suites=()
    for suite in {{ SUITES }}; do suites+=("suites/$suite"); done
    # An XCP build's A2L sits beside its ELF.
    cd testing && uv run --frozen pytest "${suites[@]}" --channel {{ CHANNEL }} --a2l "${elf%.elf}.a2l"

# Remove the cached Zephyr workspace. Frees about 2 GB.
clean-workspace:
    docker volume rm {{ WORKSPACE }}

# Fail if any of ELFS is older than any file under SOURCES, both relative to
# where just was run. A stale binary is worse than a missing one: the bus looks
# healthy while the firmware under test is not the firmware on disk.
[no-cd]
_fresh ELFS +SOURCES:
    #!/usr/bin/env bash
    set -euo pipefail
    stale=$(for elf in {{ ELFS }}; do find {{ SOURCES }} -type f -newer "$elf"; done | sort -u | head -3)
    if [ -n "$stale" ]; then
        echo "build/ is older than the sources it came from:" >&2
        echo "$stale" | sed 's/^/    /' >&2
        echo >&2
        echo "Rebuild before running, or the bench will serve the previous firmware:" >&2
        echo "    just firmware" >&2
        exit 1
    fi

# Build the firmware toolchain image. Cached by Docker after the first run.
_toolchain:
    docker image inspect {{ TOOLCHAIN }} > /dev/null 2>&1 || \
        docker build -q --build-arg ZEPHYR_VERSION={{ ZEPHYR }} -f toolchain/Dockerfile -t {{ TOOLCHAIN }} toolchain/ > /dev/null

# Create the pinned west workspace, and bring it up to date when west.yml
# changes. Cached in a Docker volume.
_west:
    #!/usr/bin/env bash
    set -euo pipefail
    manifest=$(sha256sum west.yml | cut -d' ' -f1)
    # Docker creates the volume, or the host directory, on first use.
    if [ "$(docker run --rm -v {{ WORKSPACE }}:/w alpine cat /w/.manifest 2>/dev/null)" = "$manifest" ]; then
        exit 0
    fi
    echo "==> updating the pinned Zephyr workspace to west.yml"
    docker run --rm --user root -v {{ WORKSPACE }}:/workspace -v "$PWD:/workspace/zelos-examples:ro" \
        {{ TOOLCHAIN }} bash -c \
        "cd /workspace && { [ -d .west ] || west init -l zelos-examples; } \
         && west update --narrow -o=--depth=1 && west zephyr-export \
         && echo $manifest > .manifest"
