# Shared by every bench: building the nodes, the codec, and the test runs.
#
# Benches call these recipes from their own justfiles; `cd <bench> && just` is
# where to start.

set shell := ["bash", "--noprofile", "--norc", "-euo", "pipefail", "-c"]

CANTOOLS := "41.3.1"
CANOPEN_EDITOR := "v4.2.3"
TOOLCHAIN := "zelos-examples-toolchain:v4.4.2"
BOARD := "nucleo_h753zi"
# The part on that board, for probe-rs.
CHIP := "STM32H753ZITx"
# The Docker volume holding the west workspace. Override to build two trees at once.
WORKSPACE := env("ZELOS_WEST_VOLUME", "zxws")

# Show the available recipes.
default:
    @just --list --unsorted

# Build one node into an ELF. ELF is relative to where just was run.
build NODE ELF *ARGS: _toolchain _west
    #!/usr/bin/env bash
    set -euo pipefail
    elf="{{ join(invocation_directory(), ELF) }}"
    name=$(basename "$elf" .elf)
    mkdir -p "$(dirname "$elf")"
    # An XCP build also gets the node's A2L, with this build's addresses.
    a2l="if grep -q '^CONFIG_ZELOS_XCP=y' /workspace/build/$name/zephyr/.config \
         && [ -f zelos-examples/nodes/{{ NODE }}/{{ NODE }}.a2l ]; then \
           python3 zelos-examples/tools/a2l_addresses.py zelos-examples/nodes/{{ NODE }}/{{ NODE }}.a2l \
             /out/$name.elf /out/$name.a2l; fi"
    echo "==> building $name"
    docker run --rm --user root \
        -v {{ WORKSPACE }}:/workspace -v "$PWD:/workspace/zelos-examples:ro" \
        -v "$(dirname "$elf"):/out" {{ TOOLCHAIN }} \
        bash -c "cd /workspace && west build -p always -b {{ BOARD }} \
                  -d /workspace/build/$name zelos-examples/nodes/{{ NODE }} {{ ARGS }} \
                  && cp /workspace/build/$name/zephyr/zephyr.elf /out/$name.elf \
                  && $a2l"

# Regenerate the CAN codec from the DBC. Deterministic: no timestamps.
dbc:
    # cantools stamps the generation date into a header comment, which would
    # make every regeneration differ. The version stays; the date goes.
    docker run --rm -v "$PWD:/w" -w /w python:3.12-slim bash -euc \
        'pip install --quiet cantools=={{ CANTOOLS }} \
         && python -m cantools generate_c_source --use-float -o lib/codec_bench dbc/bench.dbc \
         && sed -i -E "s/(generated by cantools version [0-9.]+) .*[0-9]{4}\./\1./" \
              lib/codec_bench/bench.h lib/codec_bench/bench.c'
    @echo "lib/codec_bench/ regenerated from dbc/bench.dbc"

# Regenerate a CANopen node's object dictionary (od/CO_OD.c, od/CO_OD.h) from
# its EDS. Builds CANopenEditor's command-line exporter at a fixed tag.
canopen-od NODE:
    # The exporter no longer emits the TIME types the v1.3 stack's CO_TIME.h
    # expects from CO_OD.h; the stack's own sample adds them by hand.
    docker run --rm -v "$PWD/nodes/{{ NODE }}/od:/od" mcr.microsoft.com/dotnet/sdk:8.0 bash -euc \
        'git clone --quiet --branch {{ CANOPEN_EDITOR }} https://github.com/CANopenNode/CANopenEditor /src 2>/dev/null \
         && dotnet publish --verbosity quiet -c Release -f net8.0 -o /edssharp /src/EDSSharp/EDSSharp.csproj > /dev/null \
         && dotnet /edssharp/EDSSharp.dll --infile /od/{{ NODE }}.eds --outfile /od/CO_OD.c --type CanOpenNode > /dev/null \
         && sed -i "/typedef domain_t *DOMAIN;/a\\
           typedef union { unsigned long long ullValue; struct { unsigned long ms:28; unsigned reserved:4; unsigned days:16; unsigned reserved2:16; }; } timeOfDay_t;\\n\
           typedef timeOfDay_t  TIME_OF_DAY;\\n\
           typedef timeOfDay_t  TIME_DIFFERENCE;" /od/CO_OD.h \
         && chown --reference=/od/{{ NODE }}.eds /od/CO_OD.c /od/CO_OD.h'
    @echo "nodes/{{ NODE }}/od/ regenerated from {{ NODE }}.eds"

# Build every node variant for the board and run every ztest suite. Reports go
# to twister-out/.
#
# The board has no simulator here, so its builds are build-only; unit tests
# run on native_sim, 64-bit so no 32-bit host libraries are needed.
twister: _toolchain _west
    #!/usr/bin/env bash
    set -euo pipefail
    roots=()
    for dir in nodes tests; do
        [ -d "$dir" ] && roots+=(-T "zelos-examples/$dir")
    done
    mkdir -p twister-out
    # Root in the container, so hand the reports back to whoever ran this.
    docker run --rm --user root \
        -v {{ WORKSPACE }}:/workspace -v "$PWD:/workspace/zelos-examples:ro" \
        -v "$PWD/twister-out:/out" {{ TOOLCHAIN }} \
        bash -c "cd /workspace && rm -rf /out/* \
                  && { west twister ${roots[*]} -p {{ BOARD }} -p native_sim/native/64 \
                         -O /out --no-clean --inline-logs; status=\$?; } \
                  ; chown -R $(id -u):$(id -g) /out; exit \$status"

# Run a testing/ suite against nodes on a Renode bench, then tear it down.
# ELFS are relative to where just was run; each runs as one node.
test-bench SUITE +ELFS:
    #!/usr/bin/env bash
    set -euo pipefail
    elfs=$(mktemp -d)
    # A project per run, so concurrent runs get their own bus.
    compose=(docker compose -p "bench-$$" -f bench/compose.yaml)
    trap '"${compose[@]}" down --remove-orphans --volumes >/dev/null 2>&1; rm -rf "$elfs"' EXIT
    names=()
    for elf in {{ ELFS }}; do
        name=$(basename "$elf")
        [ ! -e "$elfs/$name" ] || { echo "two ELFs named $name" >&2; exit 2; }
        [[ $elf = /* ]] || elf="{{ invocation_directory() }}/$elf"
        cp "$elf" "$elfs/$name"
        names+=("$name")
    done
    export BENCH_ELF_DIR=$elfs BENCH_ELFS="${names[*]}"
    "${compose[@]}" up -d --wait || { "${compose[@]}" logs renode | tail -40; exit 1; }
    # --no-deps: recreating the bus would strand the nodes in the old namespace.
    "${compose[@]}" run --rm --no-deps tester "suites/{{ SUITE }}"

# ELF is relative to where just was run.

# Flash a node with probe-rs, then run testing/ suites on a physical channel.
hil ELF CHANNEL +SUITES:
    #!/usr/bin/env bash
    set -euo pipefail
    elf="{{ join(invocation_directory(), ELF) }}"
    # Under reset: a running image can idle the core out of reach of SWD.
    probe-rs download --chip {{ CHIP }} --connect-under-reset --verify "$elf"
    probe-rs reset --chip {{ CHIP }} --connect-under-reset
    # An XCP build's A2L sits beside its ELF; suites that need it read ZELOS_A2L.
    suites=()
    for suite in {{ SUITES }}; do suites+=("suites/$suite"); done
    cd testing && ZELOS_A2L="${elf%.elf}.a2l" uv run --frozen pytest "${suites[@]}" --channel {{ CHANNEL }}

# Remove the cached Zephyr workspace. Frees about 2 GB.
clean-workspace:
    docker volume rm {{ WORKSPACE }}

# Build the firmware toolchain image. Cached by Docker after the first run.
_toolchain:
    docker build -q -f toolchain/Dockerfile -t {{ TOOLCHAIN }} toolchain/ > /dev/null

# Create the pinned west workspace, and bring it up to date when west.yml
# changes. Cached in a Docker volume.
_west:
    #!/usr/bin/env bash
    set -euo pipefail
    manifest=$(sha256sum west.yml | cut -d' ' -f1)
    if docker volume inspect {{ WORKSPACE }} >/dev/null 2>&1 && \
       [ "$(docker run --rm -v {{ WORKSPACE }}:/w alpine cat /w/.manifest 2>/dev/null)" = "$manifest" ]; then
        exit 0
    fi
    echo "==> updating the pinned Zephyr workspace to west.yml"
    docker volume create {{ WORKSPACE }} >/dev/null
    docker run --rm --user root -v {{ WORKSPACE }}:/workspace -v "$PWD:/workspace/zelos-examples:ro" \
        {{ TOOLCHAIN }} bash -c \
        "cd /workspace && { [ -d .west ] || west init -l zelos-examples; } \
         && west update --narrow -o=--depth=1 && west zephyr-export \
         && echo $manifest > .manifest"
