/**
 * @file genset.c
 *
 * @brief This source file was generated by cantools version 41.3.1.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "genset.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int genset_eec1_pack(
    uint8_t *dst_p,
    const struct genset_eec1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->actual_engine_percent_torque, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->engine_speed, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->engine_speed, 8u, 0xffu);

    return (8);
}

int genset_eec1_unpack(
    struct genset_eec1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->actual_engine_percent_torque = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->engine_speed = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->engine_speed |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);

    return (0);
}

int genset_eec1_init(struct genset_eec1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct genset_eec1_t));

    return 0;
}

uint8_t genset_eec1_actual_engine_percent_torque_encode(float value)
{
    return (uint8_t)(value - -125.0f);
}

float genset_eec1_actual_engine_percent_torque_decode(uint8_t value)
{
    return ((float)value + -125.0f);
}

bool genset_eec1_actual_engine_percent_torque_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool genset_eec1_actual_engine_percent_torque_is_in_phys_range(float value)
{
    return ((value >= -125.0f) && (value <= 125.0f));
}

uint16_t genset_eec1_engine_speed_encode(float value)
{
    return (uint16_t)(value / 0.125f);
}

float genset_eec1_engine_speed_decode(uint16_t value)
{
    return ((float)value * 0.125f);
}

bool genset_eec1_engine_speed_is_in_range(uint16_t value)
{
    return (value <= 64255u);
}

bool genset_eec1_engine_speed_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 8031.875f));
}

int genset_et1_pack(
    uint8_t *dst_p,
    const struct genset_et1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->engine_coolant_temp, 0u, 0xffu);

    return (8);
}

int genset_et1_unpack(
    struct genset_et1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->engine_coolant_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int genset_et1_init(struct genset_et1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct genset_et1_t));

    return 0;
}

uint8_t genset_et1_engine_coolant_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float genset_et1_engine_coolant_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool genset_et1_engine_coolant_temp_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool genset_et1_engine_coolant_temp_is_in_phys_range(float value)
{
    return ((value >= -40.0f) && (value <= 210.0f));
}
