/**
 * @file genset.h
 *
 * @brief This header file was generated by cantools version 41.3.1.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef GENSET_H
#define GENSET_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define GENSET_EEC1_FRAME_ID (0xcf00480u)
#define GENSET_ET1_FRAME_ID (0x18feee80u)

/* Frame lengths in bytes. */
#define GENSET_EEC1_LENGTH (8u)
#define GENSET_ET1_LENGTH (8u)

/* Extended or standard frame types. */
#define GENSET_EEC1_IS_EXTENDED (1)
#define GENSET_ET1_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define GENSET_EEC1_CYCLE_TIME_MS (100u)
#define GENSET_ET1_CYCLE_TIME_MS (1000u)

/* Signal choices. */


/* Frame Names. */
#define GENSET_EEC1_NAME "EEC1"
#define GENSET_ET1_NAME "ET1"

/* Signal Names. */
#define GENSET_EEC1_ACTUAL_ENGINE_PERCENT_TORQUE_NAME "ActualEnginePercentTorque"
#define GENSET_EEC1_ENGINE_SPEED_NAME "EngineSpeed"
#define GENSET_ET1_ENGINE_COOLANT_TEMP_NAME "EngineCoolantTemp"

/**
 * Signals in message EEC1.
 *
 * Electronic Engine Controller 1, PGN 61444.
 *
 * All signal values are as on the CAN bus.
 */
struct genset_eec1_t {
    /**
     * Range: 0..250 (-125..125 %)
     * Scale: 1
     * Offset: -125
     */
    uint8_t actual_engine_percent_torque;

    /**
     * Range: 0..64255 (0..8031.875 rpm)
     * Scale: 0.125
     * Offset: 0
     */
    uint16_t engine_speed;
};

/**
 * Signals in message ET1.
 *
 * Engine Temperature 1, PGN 65262.
 *
 * All signal values are as on the CAN bus.
 */
struct genset_et1_t {
    /**
     * Range: 0..250 (-40..210 degC)
     * Scale: 1
     * Offset: -40
     */
    uint8_t engine_coolant_temp;
};

/**
 * Pack message EEC1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int genset_eec1_pack(
    uint8_t *dst_p,
    const struct genset_eec1_t *src_p,
    size_t size);

/**
 * Unpack message EEC1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int genset_eec1_unpack(
    struct genset_eec1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EEC1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int genset_eec1_init(struct genset_eec1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t genset_eec1_actual_engine_percent_torque_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float genset_eec1_actual_engine_percent_torque_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genset_eec1_actual_engine_percent_torque_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool genset_eec1_actual_engine_percent_torque_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t genset_eec1_engine_speed_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float genset_eec1_engine_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genset_eec1_engine_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool genset_eec1_engine_speed_is_in_phys_range(float value);

/**
 * Pack message ET1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int genset_et1_pack(
    uint8_t *dst_p,
    const struct genset_et1_t *src_p,
    size_t size);

/**
 * Unpack message ET1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int genset_et1_unpack(
    struct genset_et1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ET1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int genset_et1_init(struct genset_et1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t genset_et1_engine_coolant_temp_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float genset_et1_engine_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genset_et1_engine_coolant_temp_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool genset_et1_engine_coolant_temp_is_in_phys_range(float value);


#ifdef __cplusplus
}
#endif

#endif
